# Generated by Django 5.2.17 on 2026-09-27 00:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('encrypted_body', models.TextField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=80)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('totp_secret', models.TextField(blank=True)),
                ('totp_last_step', models.BigIntegerField(default=-1)),
                ('session_version', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified')], default='new', max_length=20)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, max_length=5000)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('stage', models.CharField(choices=[('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='qualified', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('expected_close', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.contact')),
                ('source_lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.lead')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, max_length=2000)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.organization'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=5000)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=60)),
                ('entity', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('key', models.CharField(max_length=250, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=80)),
                ('sha256', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='member', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.workspace')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='crmapp_task_workspa_55ffe2_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'id'), name='task_tenant_key'), models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', True), ('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', False)), models.Q(('contact__isnull', False), ('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', True)), models.Q(('contact__isnull', True), ('deal__isnull', True), ('lead__isnull', False), ('organization__isnull', True)), models.Q(('contact__isnull', True), ('deal__isnull', False), ('lead__isnull', True), ('organization__isnull', True)), _connector='OR'), name='task_one_parent')],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_orga_workspa_89528d_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='organization_tenant_key'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_note_workspa_85f35b_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='note_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', True), ('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', False)), models.Q(('contact__isnull', False), ('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', True)), models.Q(('contact__isnull', True), ('deal__isnull', True), ('lead__isnull', False), ('organization__isnull', True)), models.Q(('contact__isnull', True), ('deal__isnull', False), ('lead__isnull', True), ('organization__isnull', True)), _connector='OR'), name='note_one_parent'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_lead_workspa_a88c0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='lead_tenant_key'),
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_impo_workspa_317232_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='importrun_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.UniqueConstraint(fields=('workspace', 'digest', 'kind'), name='import_once'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_deal_workspa_7fd92b_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='deal_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='deal_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_cont_workspa_3f38b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='contact_tenant_key'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_audi_workspa_12687e_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='auditevent_tenant_key'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['workspace', 'created_at'], name='crmapp_atta_workspa_80ae64_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='attachment_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', True), ('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', False)), models.Q(('contact__isnull', False), ('deal__isnull', True), ('lead__isnull', True), ('organization__isnull', True)), models.Q(('contact__isnull', True), ('deal__isnull', True), ('lead__isnull', False), ('organization__isnull', True)), models.Q(('contact__isnull', True), ('deal__isnull', False), ('lead__isnull', True), ('organization__isnull', True)), _connector='OR'), name='attachment_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='account_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'owner')), fields=('workspace',), name='one_active_owner'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('workspace', 'id'), name='account_tenant_key'),
        ),
    ]
