# Generated by Django 5.2.17 on 2026-09-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_row_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
